### ISSUE TITLE
Links go to the wrong place

### ISSUE THREAD

**Issue by arnau** [netlify/headlesscms.org#260]
There are many links going to the wrong place. E.g. Contentful going to quintype.

**Comment by philhawksworth** [comment]
I'm not seeing this issue, @arnau. Could you describe where you observed this?

**Comment by arnau** [comment]
Hi @philhawksworth ,

I can't reproduce it anymore. For a moment now I could see Firefox showing me the url for Contentful as Quintype and Chrome showing me Comfortable but after resizing the screen the problem went away. I have no reasonable explanation for this so probably better to close the issue :S

**Comment by michaelroper** [comment]
FWIW, I also see this... in the Closed Source section, all the ones _after_ Flotiq in this screenshot are messed up - the url you see in the status bar is me hovering over the Agility CMS card.

![image](https://user-images.githubusercontent.com/60287/82309384-a4414680-99f5-11ea-81d1-0381020be2e2.png)

Pretty sure it's a JS issue, because when I refresh the page, I actually see the Comfortable info in the right spot, then it gets swapped out with the Agility CMS info.
